apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-backend
  namespace: fap-log-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-backend
  template:
    metadata:
      labels:
        app: http-backend
    spec:
      containers:
        - name: http-backend
          image: mylosz/fap-log-viewer-backend:0.0.1
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: fap-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: fap-config
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: fap-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fap-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: fap-config
                  key: DB_NAME
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: fap-config
                  key: PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: fap-config
                  key: NODE_ENV
            - name: UPLOAD_DIR
              valueFrom:
                configMapKeyRef:
                  name: fap-config
                  key: UPLOAD_DIR
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: fap-config
                  key: NATS_URL
          volumeMounts:
            - name: uploads
              mountPath: /data/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc
