apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fap-log-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mycluster-registry:5000/mylosz/fap-log-viewer-frontend:0.0.1-test
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: fap-config
                  key: BACKEND_URL
