apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fap-ingress
  namespace: fap-log-viewer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: fap.local # Change this to your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
