apiVersion: v1
kind: ConfigMap
metadata:
  name: fap-config
  namespace: fap-log-viewer
data:
  BACKEND_URL: "http://http-backend:3000"
  DB_HOST: "postgres"
  DB_NAME: "fap_analysis"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  EMAIL_ENDPOINT: "process"
  EMAIL_PORT: "8000"
  EMAIL_URL: "email-receiver"
  NATS_URL: "nats://nats:4222"
  NODE_ENV: "production"
  PORT: "3000"
  UPLOAD_DIR: "/data/uploads"
