---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fap-secrets
  namespace: fap-log-viewer
spec:
  encryptedData:
    DB_PASSWORD: AgC7xlGs55I+lnBuzq9ISkj2EVnQemCM/2PP1cScY10D7DocTBhfQxUwCTV/akfo5baYzo94SX5k9EUI+XQGMN5+z9i+iG3YIZHq8jI0tMZldS8APzPRr/d2PORpM0FLA13CWwubQ7Lulgwa3MHAp6Fb80TR4DZVw83QojtFiIuTNRdzvzeINEDUiENcymL4N5sZnbfR+eoWCo+wTtS1RsGpooNS9KAqtEtOYNX7NyritEOpWAw+KtleU8mLo4O5GhZQTeGulAi7658AVTgkc0sV1pQ/iVizhxhDZf5JHFFULXVCJ1bF27zxb/sBqZcDoML4t4sL69eMNKduptdRmbs7FMY8lj+lJXB7wt9g5EDaj5wGWcGdeBfKunq7IuYWynFKPz4QoQk21VTablGe2rcsipAr5TU/8M1uG9GMaLB3Ht35IDOvONF9LNDt1H8PNiITD3NMa3c9iiwSX9C3aKUDHYlQE/k+CxH4uyTSoOGuIHbs9ek+xWvbsjntbIQhrjF8x2ycsGq9cyFHXfnayjz9f87oDO90lCxm104fh1zaFie2pezDtJhO5/jPTp1F9ix2QhPvtN3NXKVC0Xr+EBvVf6DE49zNgZjYOs5MjSAk419Jf4BUq6dNqHNPl8SSJj4HyFk15v9/bTVNlzcmgNeJxT0G2jQBtZakNKFl0h9nXrAjtbdVArMNFxTtI9Wqk2ECHjttIOdDvZmwGSjE/7Es/M8bOQ==
  template:
    metadata:
      creationTimestamp: null
      name: fap-secrets
      namespace: fap-log-viewer
