apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../frontend
  - ../http-backend
  - ../data-analyser
  - ../nats
  - ../postgres
  - ../namespace.yaml
  - ../configmap.yaml
  - ../storage.yaml
  - ../sealed_secret.yaml
