apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./common/*.yaml
  - ./data-analyser/*.yaml
  - ./frontend/*.yaml
  - ./http-backend/*.yaml
  - ./nats/*.yaml
  - ./postgres/*.yaml
