apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fap-log-viewer-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/miloszk9/FAP-log-viewer-devops.git
    targetRevision: HEAD
    path: k8s/fap-log-viewer/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: fap-log-viewer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
