apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 71.1.0
    helm:
      values: |
        global:
          ipFamilyPolicy: "SingleStack"
          ipFamilies: ["IPv4"]

        kubeEtcd:
          enabled: false

        kubeControllerManager:
          enabled: true
          service:
            enabled: true
            port: 10252
            targetPort: 10252

        kubeScheduler:
          enabled: true
          service:
            enabled: true
            port: 10251
            targetPort: 10251

        kubeProxy:
          enabled: true
          service:
            enabled: true
            port: 10249
            targetPort: 10249

        defaultRules:
          rules:
            etcd: false

        prometheus:
          prometheusSpec:
            retention: 24h
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            probeSelectorNilUsesHelmValues: false
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              fsGroup: 2000
            remoteWrite:
              - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
                basicAuth:
                  username:
                    name: grafana-cloud-secret
                    key: username
                  password:
                    name: grafana-cloud-secret
                    key: password

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-cloud-secret
  namespace: monitoring
spec:
  encryptedData:
    password: AgC4l3c626IubLpaI/nGYeumnyhAa6Dhjq3dQ/v2U7TWnL42+HW6Sv2cDpoY/w/m7nE/xMyrJh5XN7pxvRBgca5E0VkUlGCLjQEfH29M2S+fjef2iC7R2MJGqcQr57wZLfk5ihc3CavBsqca7vgtH/R3lCxYk4pJWR/h5t/71ZnUVm9OkP5nDYP5vXJ5qpHr8Gp0bF08K1yCZdsLK+1rMBcL5K7TEIPQ8EJ01pQXUIlyBaI3omEsgSm4+L1Vz0vfVEkUaZ0LQb2MtJ3ce5fLyzwUTJKuAAZEUlz+xPaS3BM1T+ZsCT/qwDTMMM6JJ0NJDOduNdir8budW8ymXoyMNs4ObfouvgNIo8vtHv/3y7bwddY12dVtkb4UvxMCytB+iCR0gr7j2GKf9PcmtOO4rX0Kk+tg+VfBzZM35cWqWxDXuHKL9oQGs0vNB+Up0Rysswo0HXj4t3AD4lZb2IU+8PSHML6uW9HqeCqA+bLB3+wpx9kEQTLrJYkLq0Bnc+B0EzVDkN9GtvNn/sbCSsLhw9wN769g3mDGw/88Y3Ph8JV2au3Gd4ReFKRjBummOwfpRTqhIjXArV8pwCwoNG8am655ImEuoIULoMkWZxS8BnEil/kCbpxdEyChHu/ajBzXIy2IrS3Jk3hllfbrRoOd1w/Hx/uEC08D7FNZzybAjWL80CI4GiHWmVVtxsggkdCmaVeoUsKGJCcIRmJolN8cJbkRiLJ72AsA7TLZb+Z/zBetpmqXiaHCEKZYEocV09il7NO37a5w2P7yZGX+1cUNZ7qoVI3WkSW4P0BRBH/XOb+POyLRNE/9zjk0cp6Wv7EWOJEZO60Et/vdak/bgrOvJ6HbOi+gY9Nmwi1vHAwFijYwFFiWf2HUjyFCX5sqFiIh1OZY1iltpqH7NDB+Gh35YtDP1Y25DFZQTXxfEG26
    username: AgCrc2oDG6Bm6gNCNw4wa5TemLxlNMXldkHRZW3hyW4Ek0mRgEjf6PhIMGIUuEGdL4ntwZYkAmRuoW3ohPIF2i3252mXtPP853TWNx1Fre3ZEHY1sw6SyfIEr6ngr+mdhQ+jvt2nIULgDXNkwYYkPhuEwq/bGDq2y8wilzWhgD9EBtt5Wfr1RzamzdxOxo4cCk89jJxjE+RAo22xEomLn1/P/hJm3Bogc9P8KZHdBv09L4ha4UP81YfNYm2FBjYRTSHWGGcUXml9c/AuQQXJax7STls6i1grKea5docgdaQjp19Lyd3lpAjJY5mv3MHJ0BzWkK19woeL7whIk7/tgGD5sLh//dZgN9wDTYYdQrVrxjF+bdRysB7F/7VpYJQ3QJPhZ6Beb5oL3PcB7V5RwUot2lcT+/UzPavw3ADJS+4e1l1gKN9ePTCUkS0OTsuq/fxk7bGTQlTYrp7qjTS8WZsYNU3hb7fUQLPQBkZe41aEKlIuaBmfxdo94L/GAYNXUaXjOtCHBgJWslV4fPQlZZoDUp43oj9wOFRHSw9sP11h80vlO734KuD6qn1vnSRqoQKfka826YevTzsCf2Dr1DpYmODSdcB3lvFR8SqG9Mnsn3bpnuUFKIQUgaRJ6UCD11xYZ+ocAQmjKsjTABgp+MLUDcT6d9A6gYqn02VWTNl/xopAJ3NLSgwRIjwHxyxqrT67hG5YjxUi
  template:
    metadata:
      creationTimestamp: null
      name: grafana-cloud-secret
      namespace: monitoring
